/** Every visible string lives here in both languages. */
export const STRINGS = {
  en: {
    "app.name": "Mandi Mitra",
    "app.tagline": "Daily list, stock and kaccha parcha",

    "common.save": "Save", "common.saving": "Saving…", "common.cancel": "Cancel",
    "common.add": "Add", "common.edit": "Edit", "common.delete": "Delete",
    "common.search": "Search", "common.close": "Close", "common.back": "Back",
    "common.next": "Next", "common.done": "Done", "common.retry": "Retry",
    "common.yes": "Yes", "common.no": "No", "common.optional": "optional",
    "common.required": "required", "common.active": "Active", "common.inactive": "Inactive",
    "common.showInactive": "Show inactive", "common.noResults": "Nothing found",
    "common.loading": "Loading…", "common.all": "All", "common.none": "None",
    "common.confirmDelete": "Delete this?", "common.deleted": "Deleted",
    "common.saved": "Saved", "common.copy": "Copy", "common.copied": "Copied",
    "common.hindi": "Hindi",
    "hindi.accept": "Use the Hindi spelling",
    "gemini.usedOf": "Gemini today: {used} of {limit} reads used", "gemini.usedToday": "Gemini today: {used} reads used",
    "gemini.onePerPage": "each page is one read", "gemini.resets": "resets {reset}",
    "gemini.exhausted": "Today's {limit} free Gemini reads are used up — they come back at {reset}",
    "gemini.exhaustedSub": "You can still upload now and read the sheet after that. To stop hitting this, enable billing on the Google Cloud project that owns this API key; a page then costs well under a rupee.",
    "gemini.willUse": "This will use {n} reads", "hindi.reading": "in Hindi:", "hindi.hint": "Enter or Tab to use it, Esc to keep English",
    "adati.showingOf": "Showing {n} of {total}", "adati.typeToSearch": "Keep typing to narrow it down", "common.hinglish": "Hinglish", "common.english": "English",
    "common.language": "Language", "common.theme": "Theme",
    "common.themeLight": "Light", "common.themeDark": "Dark", "common.themeSystem": "System",
    "common.perBag": "per bag", "common.perQtl": "per quintal", "common.perTruck": "per truck",
    "common.quintal": "qtl", "common.bags": "bags", "common.rupees": "Rs",
    "common.somethingWrong": "Something went wrong",

    "nav.dashboard": "Dashboard", "nav.dailyList": "Daily list", "nav.scan": "Scan & OCR",
    "nav.loads": "Loads", "nav.parcha": "Kaccha parcha", "nav.stock": "Stock",
    "nav.suppliers": "Suppliers", "nav.mills": "Mills", "nav.commodities": "Commodities",
    "nav.ledger": "Ledger", "nav.payments": "Payments", "nav.users": "Users",
    "nav.roles": "Roles", "nav.audit": "Audit trail", "nav.settings": "Settings",
    "nav.masters": "Masters", "nav.operations": "Operations", "nav.accounts": "Accounts",
    "nav.admin": "Administration",
    "nav.hideSidebar": "Hide the menu", "nav.showSidebar": "Show the menu", "nav.pinSidebar": "Keep the menu open",

    "auth.welcome": "Welcome", "auth.setupTitle": "Set up Mandi Mitra",
    "auth.setupSub": "This runs once. You can change everything later.",
    "auth.yourName": "Your name", "auth.yourNameHi": "Your name in Hindi",
    "auth.phone": "Phone", "auth.pin": "PIN", "auth.pinAgain": "Confirm PIN",
    "auth.pinHelp": "4 to 6 digits. You will use this to sign in.",
    "auth.pinMismatch": "The two PINs do not match",
    "auth.businessName": "Business name", "auth.businessNameHi": "Business name in Hindi",
    "auth.shortCode": "Short code", "auth.shortCodeHelp": "Shows on the parcha, e.g. VLDM",
    "auth.createAccount": "Create account", "auth.signIn": "Sign in",
    "auth.whoAreYou": "Who is signing in?", "auth.enterPin": "Enter PIN",
    "auth.wrongPin": "Wrong PIN", "auth.signOut": "Sign out",
    "auth.changePin": "Change PIN", "auth.currentPin": "Current PIN", "auth.newPin": "New PIN",
    "auth.switchUser": "Switch user",

    "biz.switch": "Switch business", "biz.add": "Add business",
    "biz.addSub": "A second firm, e.g. V C Enterprise. Suppliers, mills and stock stay separate.",
    "biz.profile": "Business profile", "biz.address": "Address",
    "biz.addressLine1": "Address line 1", "biz.addressLine2": "Address line 2",
    "biz.city": "City", "biz.district": "District", "biz.state": "State",
    "biz.pincode": "PIN code", "biz.gstin": "GSTIN", "biz.mandiLicense": "Mandi licence no",
    "biz.panNo": "PAN", "biz.current": "Current business",

    "adati.title": "Suppliers", "adati.sub": "The small businesses you buy from",
    "adati.add": "Add supplier", "adati.edit": "Edit supplier",
    "adati.nameHi": "Name in Hindi", "adati.nameHinglish": "Name in Hinglish",
    "adati.nameHiHelp": "Write it exactly as your employee writes it on the sheet",
    "adati.nameHinglishHelp": "Filled in automatically. Edit it and we stop changing it.",
    "adati.autoFilled": "auto", "adati.edited": "edited by you",
    "adati.resetAuto": "Use auto spelling",
    "adati.village": "Village", "adati.phone": "Phone",
    "adati.accountNo": "Account no", "adati.ifsc": "IFSC",
    "adati.openingBalance": "Opening balance", "adati.notes": "Notes",
    "adati.aliases": "Known spellings", "adati.aliasCount": "spellings learnt",
    "adati.aliasHelp": "Every correction the OCR review screen makes is remembered here, so the same misreading resolves by itself next time.",
    "adati.aliasAdd": "Add a spelling", "adati.aliasHits": "matched",
    "adati.aliasSourceCanonical": "main name", "adati.aliasSourceCorrection": "correction",
    "adati.aliasSourceRename": "old name", "adati.aliasSourceOcr": "from OCR",
    "adati.empty": "No suppliers yet", "adati.emptySub": "Add the names from your daily list, or import them from a scanned sheet.",
    "adati.regenerate": "Redo auto spellings",
    "adati.regenerateDone": "Updated {n} of {total}. Names you edited were left alone.",
    "adati.searchPlaceholder": "Search by name, village or phone",
    "adati.deactivated": "This supplier has slips, so it was made inactive instead of deleted.",
    "adati.count": "{n} suppliers",

    "merchant.title": "Mills & merchants", "merchant.sub": "Who you load for, and the terms each one charges",
    "merchant.add": "Add mill", "merchant.edit": "Edit mill",
    "merchant.code": "Short code", "merchant.codeHelp": "Appears on the sheet header, e.g. GRM or LB",
    "merchant.name": "Mill name", "merchant.nameHi": "Mill name in Hindi",
    "merchant.contactPerson": "Contact person", "merchant.charges": "Charge terms",
    "merchant.chargesSub": "These drive every number on the kaccha parcha",
    "merchant.weights": "Weights & bardana",
    "merchant.katauti": "Katauti when buying",
    "merchant.katautiHelp": "Deducted on your daily list. Checked across 45 rows of your sheets: 1 kg per quintal, on gross rounded to the nearest quintal.",
    "merchant.katautiMode.per_quintal_rounded": "Per quintal, gross rounded",
    "merchant.katautiMode.per_quintal_exact": "Per quintal, exact",
    "merchant.katautiMode.none": "No katauti",
    "merchant.millBardana": "Bardana at the mill", "merchant.millBardanaHelp": "How this mill weighs an empty bag. Your 20-09 parcha works out to 0.57 kg.",
    "merchant.adat": "Kacchi adat", "merchant.labour1": "Labour", "merchant.labour2": "Labour (second slab)",
    "merchant.sutli": "Sutli", "merchant.gaushala": "Gaushala", "merchant.mandiTax": "Mandi tax",
    "merchant.commission": "Commission", "merchant.gatePass": "Gate pass",
    "merchant.extraCharges": "Other charges", "merchant.extraAdd": "Add a charge",
    "merchant.dara": "Dara", "merchant.advance": "Advance", "merchant.rounding": "Grand total rounding",
    "merchant.parchaLayout": "Parcha layout",
    "merchant.chargedOn": "charged on", "merchant.base.amount": "Goods value only",
    "merchant.base.amount_plus_adat": "Goods value + adat",
    "merchant.base.total_before_charge": "Running total",
    "merchant.weightBase.gross": "Gross weight (dharam kanta)", "merchant.weightBase.net": "Net weight",
    "merchant.daraMode.none": "Not used", "merchant.daraMode.per_bag": "Per bag",
    "merchant.daraMode.per_qtl": "Per quintal", "merchant.daraMode.pct": "Percentage",
    "merchant.daraMode.manual": "Typed in per load",
    "merchant.daraInTotal": "Include dara in grand total",
    "merchant.daraInTotalHelp": "Your sample parcha prints dara but leaves it out of the grand total.",
    "merchant.advanceTreatment": "Advance on the parcha",
    "merchant.advance.add": "Added to the total", "merchant.advance.subtract": "Deducted from the total",
    "merchant.advance.exclude": "Not shown",
    "merchant.advanceHelp": "Your 20-09 parcha adds it — freight you paid and recover from the mill.",
    "merchant.rounding.none": "No rounding", "merchant.rounding.nearest_rupee": "Nearest rupee",
    "merchant.rounding.up_rupee": "Round up to rupee", "merchant.rounding.nearest_ten": "Nearest ten rupees",
    "merchant.preview": "Live preview", "merchant.previewSub": "A sample load run through these terms",
    "merchant.previewGross": "Gross", "merchant.previewBags": "Bags", "merchant.previewRate": "Rate",
    "merchant.previewNet": "Net", "merchant.previewAdvance": "Advance", "merchant.previewDara": "Dara",
    "merchant.empty": "No mills yet", "merchant.emptySub": "Add the mills you load for, with the charges each one applies.",
    "merchant.deactivated": "This mill has loads, so it was made inactive instead of deleted.",
    "merchant.enabled": "Applied", "merchant.disabled": "Not applied",
    "merchant.paymentTerms": "Payment terms (days)",
    "merchant.notInGrandTotal": "not in grand total",

    "jins.title": "Commodities", "jins.sub": "The varieties you trade",
    "jins.add": "Add commodity", "jins.code": "Code", "jins.name": "Name",
    "jins.crop": "Crop", "jins.crop.paddy": "Paddy", "jins.crop.wheat": "Wheat",
    "jins.crop.maize": "Maize", "jins.crop.other": "Other",

    "users.title": "Users", "users.sub": "Who can use this, and what they may do",
    "users.add": "Add user", "users.edit": "Edit user", "users.role": "Role",
    "users.setPin": "Set PIN", "users.resetPin": "Reset PIN", "users.unlock": "Unlock",
    "users.locked": "Locked", "users.lockedUntil": "Locked for {min} min",
    "users.owner": "Owner", "users.overrides": "Extra permissions",
    "users.overridesSub": "On top of the role. A deny always wins.",
    "users.effectivePerms": "{n} permissions",
    "users.lastOwner": "This is the only Owner. Make someone else an Owner first.",
    "users.you": "you",

    "roles.title": "Roles & permissions", "roles.sub": "Exactly what each role may do",
    "roles.add": "Add role", "roles.key": "Key", "roles.label": "Name",
    "roles.builtIn": "built-in", "roles.userCount": "{n} users",
    "roles.ownerLocked": "The Owner role always keeps every permission.",
    "roles.selectAll": "Select all", "roles.clearAll": "Clear all",
    "roles.permCount": "{n} of {total}",

    "audit.title": "Audit trail", "audit.sub": "Every change, who made it and what it was before",
    "audit.filterEntity": "Type", "audit.filterUser": "User", "audite.filterAction": "Action",
    "audit.filterAction": "Action", "audit.loadMore": "Load older",
    "audit.empty": "Nothing recorded yet", "audit.changed": "Changed",
    "audit.before": "Before", "audit.after": "After", "audit.noChange": "no field changed",
    "audit.searchPlaceholder": "Search by name, user or action",
    "audit.readOnly": "This log cannot be edited or deleted, by anyone.",

    "dash.title": "Dashboard", "dash.comingSoon": "Being built next",
    "dash.setupChecklist": "Finish setting up", "dash.setupSub": "A few things to fill in before the daily list is useful",
    "dash.stepBusiness": "Business address and licence", "dash.stepMills": "Add the mills you load for",
    "dash.stepSuppliers": "Add your suppliers", "dash.stepUsers": "Add your staff",
    "dash.stepDone": "Done", "dash.stepTodo": "To do",
    "dash.suppliers": "Suppliers", "dash.mills": "Mills", "dash.commodities": "Commodities", "dash.staff": "Staff",

    "daily.title": "Daily list", "daily.sub": "One row per supplier slip",
    "daily.date": "Date", "daily.today": "Today", "daily.prevDay": "Previous day", "daily.nextDay": "Next day",
    "daily.mill": "Mill", "daily.jins": "Commodity", "daily.allMills": "All mills", "daily.noMill": "No mill yet",
    "daily.sheetHeader": "Sheet header", "daily.sheetHeaderSub": "Matches the top of your paper sheet",
    "daily.rst": "Kanta slip (RST)", "daily.rstPlaceholder": "slip no.", "daily.rstRepeated": "This slip no. appears more than once today", "daily.supplier": "Adati name", "daily.gross": "Dharam kanta",
    "daily.bags": "Katauti", "daily.katautiWt": "Deduction", "daily.net": "Net weight",
    "daily.rate": "Rate", "daily.amount": "Amount",
    "daily.newRow": "New row", "daily.addRow": "Add row", "daily.saveRow": "Save row",
    "daily.totals": "Total", "daily.rowCount": "{n} rows", "daily.weightedAvg": "Weighted average rate",
    "daily.enterToSave": "Enter to save", "daily.escToCancel": "Esc to cancel",
    "daily.keyboardHelp": "Type and press Enter to move through the row. Enter on Rate saves it and starts the next row.",
    "daily.searchSupplier": "Type a name in Hindi or English",
    "daily.noSupplierFound": "No supplier matches", "daily.createSupplier": "Add \"{name}\" as a new supplier",
    "daily.duplicateRst": "RST {rst} is already used on this date",
    "daily.lastRate": "Last rate", "daily.lastRateOn": "on {date}",
    "daily.onLoad": "On a load", "daily.lockedRow": "This slip is on a load, so it cannot be changed",
    "daily.mismatchRows": "{n} rows do not add up", "daily.recompute": "Recompute the day",
    "daily.recomputeDone": "Checked {scanned} rows, corrected {changed}.",
    "daily.empty": "Nothing entered for this date",
    "daily.emptySub": "Start typing in the row below, or scan the sheet.",
    "daily.reassign": "Move to mill", "daily.selectedRows": "{n} selected", "daily.selectAllN": "Select all {n}",
    "daily.fromScan": "Open the scan this row came from",
    "daily.netAuto": "Net is calculated, never typed",
    "daily.confirmDeleteRow": "Delete RST {rst}?",
    "daily.sheetTotal": "Your sheet total", "daily.sheetTotalSub": "Type what is written at the bottom of the paper, to cross-check",
    "daily.matches": "Matches", "daily.differsBy": "Differs by {amount}",
    "daily.perBag": "{kg} kg per quintal",
    "daily.katautiAuto": "Katauti comes from the gross weight — type over it only if your sheet differs",
    "daily.katautiEdited": "overridden",
    "daily.needMill": "Pick the mill from your sheet header first",
    "daily.needSupplier": "Pick a supplier", "daily.needGross": "Enter the dharam kanta weight",
    "daily.rateLocked": "You do not have permission to set the rate",
    "daily.ratePending": "Rate not set", "daily.ratePendingRows": "{n} rows have no rate yet",
    "daily.ratePendingSub": "They are left out of the weighted average, because that average becomes the rate on the parcha.",
    "daily.bagWarning": "Check the bag count", "daily.bagWarningRows": "{n} rows have an odd weight per bag",
    "daily.bagWarningSub": "A bag usually holds 35 to 45 kg. These work out very different.",
    "daily.perBagAvg": "{kg} kg per bag", "daily.pricedNet": "Priced net weight",
    "settings.numbers": "Numbers & currency", "settings.numbersSub": "How every figure is shown across the app",
    "settings.numberFormat": "Digit grouping",
    "settings.format.indian": "Indian — 10,81,909.36", "settings.format.international": "International — 1,081,909.36",
    "settings.format.plain": "None — 1081909.36",
    "settings.showSymbol": "Show currency symbol", "settings.showSymbolSub": "Adds the symbol before every amount",
    "settings.currencySymbol": "Currency symbol", "settings.symbolSpacing": "Space after the symbol",
    "settings.moneyDecimals": "Paise on amounts", "settings.weightDecimals": "Decimals on weight",
    "settings.rateDecimals": "Decimals on rate", "settings.negativeStyle": "Negative amounts",
    "settings.negative.minus": "Minus sign — -21,213.91", "settings.negative.brackets": "Brackets — (21,213.91)",
    "settings.showWordAmount": "Show lakh / crore next to big totals",
    "settings.weightUnitLabel": "Weight unit label", "settings.defaultKatauti": "Default katauti per bag",
    "settings.defaultKatautiSub": "Used on the daily list when no mill is chosen. Your sheets use 1 kg.",
    "settings.preview": "Preview", "settings.decimals0": "None", "settings.decimals2": "Two", "settings.decimals3": "Three",
    "settings.gemini": "Gemini API key", "settings.geminiSub": "Used to read your scanned sheets",
    "settings.apiKey": "API key", "settings.apiKeyHelp": "From aistudio.google.com/apikey. It starts with \"AIza\". Stored encrypted; never shown again after saving.",
    "settings.copyKeyFrom": "Copy the key from {name}", "settings.copyKeyDone": "Key copied",
    "settings.apiKeySet": "Key saved", "settings.apiKeyNone": "No key yet",
    "settings.apiKeyUnreadable": "A key is stored but cannot be decrypted. Enter it again.",
    "settings.replaceKey": "Replace key", "settings.removeKey": "Remove key",
    "settings.testKey": "Test connection", "settings.testOk": "Working — replied in {ms} ms",
    "settings.testFail": "Failed", "settings.model": "Model", "settings.fallbackModel": "Fallback model",
    "settings.fallbackModelSub": "Retried on this model when the first pass reads a page poorly",
    "settings.fallbackBelow": "Retry below confidence",
    "dlp.title": "Daily list settings", "dlp.sub": "Applies to this screen only",
    "dlp.newRow": "Blank entry row", "dlp.newRow.top": "At the top", "dlp.newRow.bottom": "At the bottom",
    "dlp.sortOrder": "Row order", "dlp.sort.entry": "As entered", "dlp.sort.rstAsc": "RST no, low to high",
    "dlp.sort.rstDesc": "RST no, high to low", "dlp.sort.newestFirst": "Newest first",
    "dlp.density": "Row height", "dlp.density.compact": "Compact", "dlp.density.normal": "Normal",
    "dlp.uiColumns": "Columns on screen", "dlp.exportColumns": "Columns in the download",
    "dlp.locked": "always shown", "dlp.carryRate": "Carry the rate forward to the next row",
    "dlp.showRunningTotal": "Show the running total",
    "dlp.scope": "Where to keep this", "dlp.scopeSession": "This browser only",
    "dlp.scopeUser": "Save for me everywhere", "dlp.scopeSessionSub": "Lost when you clear the browser. Nothing is saved to the server.",
    "dlp.scopeUserSub": "Follows your login on any machine.",
    "dlp.sessionActive": "Using a browser-only layout", "dlp.clearSession": "Drop the browser layout",
    "dlp.reset": "Back to defaults", "dlp.applySession": "Use for now", "dlp.applyUser": "Save for me",
    "dlp.rounding": "Katauti rounding", "dlp.rounding.half_up": "Half up — 32.50 becomes 33 (owner's favour)",
    "dlp.rounding.up": "Always up — 32.10 becomes 33", "dlp.rounding.down": "Always down — 32.90 becomes 32",
    "dlp.rounding.half_even": "Half to even — 32.50 becomes 32",
    "dlp.roundingSub": "Half up matched all 45 rows of your sheets, and every .50 rounds up.",
    "scan.title": "Scan & OCR", "scan.sub": "Read a handwritten sheet, check it, then add it to the daily list",
    "scan.upload": "Upload sheet", "scan.uploadSub": "A photo or scan of your handwritten daily list — the page with ADATI NAME, RST NO, DHARAM KANTA, KATAUTI, NET WEIGHT and RATE. JPG, JPEG, PNG, WEBP, HEIC or PDF. Pick several pages at once; a two-page sheet is read as one list.",
    "scan.dropHere": "Drop the scans here, or click to choose (several at once is fine)",
    "scan.chooseFiles": "Choose files",
    "scan.noFilesPicked": "No file was picked. Try again, or drag the scan onto the box.",
    "scan.uploading": "Uploading {n} page(s)…", "scan.pages": "{n} pages", "scan.page": "Page {n}",
    "scan.read": "Read the sheet", "scan.reading": "Reading the sheet…",
    "scan.readingSub": "This takes about half a minute for a full page. You can switch to another screen — it keeps running and the rows will be here when you come back.",
    "scan.uploadingNow": "Uploading…", "scan.rereadWith": "Read again with",
    "scan.status.uploaded": "Not read yet", "scan.status.reading": "Reading",
    "scan.status.review": "Waiting for review", "scan.status.committed": "Added to daily list",
    "scan.status.failed": "Failed",
    "scan.filterStatus": "Status", "scan.filterFrom": "From", "scan.filterTo": "To",
    "scan.filterMill": "Mill", "scan.clearFilters": "Clear filters",
    "scan.empty": "No scans yet", "scan.emptySub": "Scan or photograph your daily sheet and upload it here.",
    "scan.noKey": "Add your Gemini API key in Settings before scanning",
    "scan.review": "Review",
    "scan.showScan": "Show the scan", "scan.hideScan": "Hide the scan",
    "scan.conf": "Read", "scan.issues": "Checks", "scan.rowNo": "#",
    "scan.extracted": "Extracted rows — edit anything before approving",
    "scan.notFound": "This scan is not in the current business",
    "scan.notFoundSub": "A scan belongs to the business it was uploaded under. Switch business, or pick another scan.",
    "scan.findIt": "Find where it is", "scan.foundInBusiness": "It belongs to {name}.",
    "scan.switchAndOpen": "Switch to {name} and open it",
    "scan.createMissing": "Add {n} new suppliers",
    "scan.suppliersCreated": "Added {created} suppliers and filled {linked} rows.",
    "scan.rowsWord": "rows", "scan.needSuppliers": "Pick the supplier on {n} rows", "scan.reviewSub": "Check each row against the paper, then add it to the daily list",
    "scan.summary.total": "Rows read", "scan.summary.clean": "Clean", "scan.summary.warnings": "To check",
    "scan.summary.blocking": "Must fix", "scan.summary.excluded": "Dropped",
    "scan.summary.netAgree": "Net matches the paper", "scan.summary.names": "Names matched",
    "scan.summary.confidence": "Reader confidence",
    "scan.netAgreeHelp": "Rows where the net weight written on the paper equals our own calculation. These are almost certainly read correctly.",
    "scan.commit": "Add to daily list", "scan.committing": "Adding…",
    "scan.commitBlocked": "Fix {n} rows first", "scan.committed": "Added {n} rows to {date}",
    "scan.learned": "{n} new spellings learnt",
    "scan.openDaily": "Open the daily list", "scan.exclude": "Drop this row", "scan.include": "Put it back",
    "scan.struck": "Struck through on the paper", "scan.pickName": "Pick the supplier",
    "scan.matchedBy.alias": "known spelling", "scan.matchedBy.normkey": "close spelling", "scan.matchedBy.fuzzy": "similar", "scan.pickedByYou": "picked by you",
    "scan.matchedBy.model": "read from list", "scan.clickToChange": "Click to change the supplier",
    "scan.whyGross": "The paper's net weight is {net}, which does not match this gross. Check the gross, or click the star to accept it.",
    "scan.readingPage": "Reading page {n} of {total}…", "scan.readingMore": "Rows appear here page by page as each one is read.",
    "scan.dragToResize": "Drag to resize",
    "scan.fixRedStars": "Fix the {n} red boxes first",
    "scan.slipCol": "Kanta slip (RST)",
    "scan.fix.rstMissing": "Type the kanta slip no.",
    "scan.fix.rstExists": "Already on the daily list for this date — drop this row",
    "scan.fix.pickName": "Pick the supplier",
    "scan.fix.grossMissing": "Type the dharam kanta weight",
    "scan.fix.netNonPositive": "Weight too small — check the decimal",
    "scan.orderTitle": "Put the pages in order", "scan.orderSub": "They are read as one list, top to bottom, page 1 first",
    "scan.orderHint": "Use the arrows to move a page. Page 1 is the one with the sheet header.",
    "scan.moveUp": "Earlier", "scan.moveDown": "Later", "scan.readInOrder": "Read in this order",
    "scan.rowsOnPage": "{n} rows",
    "scan.ocrSaid": "Read as", "scan.wasRead": "read as", "scan.restoreRead": "Put back what was read from the sheet", "scan.derived": "Calculated", "scan.sheetSaid": "On the paper",
    "scan.needDate": "Set the sheet date", "scan.needJins": "Set the commodity",
    "scan.header": "Sheet header", "scan.headerRead": "The reader saw",
    "scan.zoomIn": "Zoom in", "scan.zoomOut": "Zoom out", "scan.fit": "Fit",
    "scan.deleteScan": "Delete this scan", "scan.confirmDelete": "Delete this scan and its images?",
    "scan.rowsOnly": "Show only", "scan.rowsAll": "All rows", "scan.rowsIssues": "Rows with issues",
    "scan.rowsBlocking": "Rows that must be fixed", "scan.rowsClean": "Clean rows",
    "scan.failedTitle": "The sheet could not be read", "scan.tryAgain": "Try again",
    "scan.costNote": "Tokens: {in} in, {out} out",
    "issue.rst_missing": "RST number could not be read",
    "issue.rst_exists": "RST {rst} is already entered for this date",
    "issue.rst_dupe": "RST {rst} appears twice on this sheet",
    "issue.name_unresolved": "No supplier matches \"{name}\"",
    "issue.name_missing": "Supplier name could not be read",
    "issue.name_fuzzy": "Matched \"{name}\" by similarity — check it",
    "issue.gross_missing": "Gross weight could not be read",
    "issue.net_nonpositive": "Net weight works out to zero or less",
    "issue.gross_large": "Gross weight looks very large for one slip",
    "issue.gross_small": "Gross weight is under one quintal — check the decimal point",
    "issue.net_mismatch": "The paper's net weight differs from the calculation by {diff} qtl",
    "issue.katauti_mismatch": "Katauti on the paper is {sheet}, calculated {calculated}",
    "issue.rate_missing": "Rate could not be read — it can be filled in later",
    "issue.rate_range": "Rate is outside the usual range — check it",
    "issue.low_confidence": "The reader was unsure about this row",
    "err.noPermission": "You do not have permission for this",
    "err.noPermissionSub": "Ask an Owner to give you the {perm} permission.",
    "err.offline": "Cannot reach the server",
    "err.offlineSub": "The local service may have stopped. Check that it is running, then retry.",
    "err.crashed": "This screen ran into a problem", "err.crashedSub": "Nothing was lost. Reload the screen, or go back to the dashboard.",
    "err.reload": "Reload",
  },

  hi: {
    "app.name": "मंडी मित्र",
    "app.tagline": "दैनिक सूची, स्टॉक और कच्चा पर्चा",

    "common.save": "सहेजें", "common.saving": "सहेज रहे हैं…", "common.cancel": "रद्द करें",
    "common.add": "जोड़ें", "common.edit": "बदलें", "common.delete": "हटाएँ",
    "common.search": "खोजें", "common.close": "बंद करें", "common.back": "पीछे",
    "common.next": "आगे", "common.done": "पूरा", "common.retry": "फिर कोशिश करें",
    "common.yes": "हाँ", "common.no": "नहीं", "common.optional": "वैकल्पिक",
    "common.required": "आवश्यक", "common.active": "सक्रिय", "common.inactive": "निष्क्रिय",
    "common.showInactive": "निष्क्रिय दिखाएँ", "common.noResults": "कुछ नहीं मिला",
    "common.loading": "लोड हो रहा है…", "common.all": "सभी", "common.none": "कोई नहीं",
    "common.confirmDelete": "इसे हटाएँ?", "common.deleted": "हटा दिया",
    "common.saved": "सहेज लिया", "common.copy": "कॉपी", "common.copied": "कॉपी हो गया",
    "common.hindi": "हिन्दी",
    "hindi.accept": "हिन्दी वर्तनी लगाएँ",
    "gemini.usedOf": "आज Gemini: {limit} में से {used} पढ़ाई हो चुकी", "gemini.usedToday": "आज Gemini: {used} पढ़ाई हो चुकी",
    "gemini.onePerPage": "हर पन्ना एक पढ़ाई", "gemini.resets": "{reset} पर फिर से",
    "gemini.exhausted": "आज की {limit} मुफ़्त Gemini पढ़ाई ख़त्म — {reset} पर फिर मिलेंगी",
    "gemini.exhaustedSub": "अभी अपलोड कर सकते हैं और उसके बाद पढ़ सकते हैं। यह रोक हटाने के लिए, जिस Google Cloud प्रोजेक्ट की यह API कुंजी है उस पर बिलिंग चालू करें; तब एक पन्ना एक रुपये से काफ़ी कम पड़ता है।",
    "gemini.willUse": "इसमें {n} पढ़ाई लगेंगी", "hindi.reading": "हिन्दी में:", "hindi.hint": "लगाने के लिए Enter या Tab, अंग्रेज़ी रखने के लिए Esc",
    "adati.showingOf": "{total} में से {n} दिख रहे", "adati.typeToSearch": "और लिखें ताकि सूची छोटी हो", "common.hinglish": "हिंग्लिश", "common.english": "अंग्रेज़ी",
    "common.language": "भाषा", "common.theme": "थीम",
    "common.themeLight": "उजला", "common.themeDark": "गहरा", "common.themeSystem": "सिस्टम",
    "common.perBag": "प्रति बोरा", "common.perQtl": "प्रति क्विंटल", "common.perTruck": "प्रति ट्रक",
    "common.quintal": "क्विं", "common.bags": "बोरे", "common.rupees": "रु",
    "common.somethingWrong": "कुछ गड़बड़ हो गई",

    "nav.dashboard": "डैशबोर्ड", "nav.dailyList": "दैनिक सूची", "nav.scan": "स्कैन व OCR",
    "nav.loads": "लोड", "nav.parcha": "कच्चा पर्चा", "nav.stock": "स्टॉक",
    "nav.suppliers": "आढ़ती", "nav.mills": "मिल", "nav.commodities": "जिंस",
    "nav.ledger": "खाता", "nav.payments": "भुगतान", "nav.users": "उपयोगकर्ता",
    "nav.roles": "भूमिका", "nav.audit": "ऑडिट", "nav.settings": "सेटिंग",
    "nav.masters": "मास्टर", "nav.operations": "कामकाज", "nav.accounts": "खाता",
    "nav.admin": "प्रशासन",
    "nav.hideSidebar": "मेन्यू छिपाएँ", "nav.showSidebar": "मेन्यू दिखाएँ", "nav.pinSidebar": "मेन्यू खुला रखें",

    "auth.welcome": "स्वागत है", "auth.setupTitle": "मंडी मित्र शुरू करें",
    "auth.setupSub": "यह एक बार होता है। सब कुछ बाद में बदल सकते हैं।",
    "auth.yourName": "आपका नाम", "auth.yourNameHi": "आपका नाम हिन्दी में",
    "auth.phone": "फ़ोन", "auth.pin": "पिन", "auth.pinAgain": "पिन दोबारा",
    "auth.pinHelp": "4 से 6 अंक। इससे आप लॉगिन करेंगे।",
    "auth.pinMismatch": "दोनों पिन एक जैसे नहीं हैं",
    "auth.businessName": "व्यापार का नाम", "auth.businessNameHi": "व्यापार का नाम हिन्दी में",
    "auth.shortCode": "छोटा कोड", "auth.shortCodeHelp": "पर्चे पर दिखेगा, जैसे VLDM",
    "auth.createAccount": "खाता बनाएँ", "auth.signIn": "लॉगिन",
    "auth.whoAreYou": "कौन लॉगिन कर रहा है?", "auth.enterPin": "पिन डालें",
    "auth.wrongPin": "पिन गलत है", "auth.signOut": "लॉगआउट",
    "auth.changePin": "पिन बदलें", "auth.currentPin": "वर्तमान पिन", "auth.newPin": "नया पिन",
    "auth.switchUser": "उपयोगकर्ता बदलें",

    "biz.switch": "व्यापार बदलें", "biz.add": "व्यापार जोड़ें",
    "biz.addSub": "दूसरी फर्म, जैसे V C Enterprise। आढ़ती, मिल और स्टॉक अलग रहेंगे।",
    "biz.profile": "व्यापार प्रोफ़ाइल", "biz.address": "पता",
    "biz.addressLine1": "पता पंक्ति 1", "biz.addressLine2": "पता पंक्ति 2",
    "biz.city": "शहर", "biz.district": "ज़िला", "biz.state": "राज्य",
    "biz.pincode": "पिन कोड", "biz.gstin": "GSTIN", "biz.mandiLicense": "मंडी लाइसेंस नं",
    "biz.panNo": "पैन", "biz.current": "वर्तमान व्यापार",

    "adati.title": "आढ़ती", "adati.sub": "जिनसे आप माल खरीदते हैं",
    "adati.add": "आढ़ती जोड़ें", "adati.edit": "आढ़ती बदलें",
    "adati.nameHi": "नाम हिन्दी में", "adati.nameHinglish": "नाम हिंग्लिश में",
    "adati.nameHiHelp": "जैसा आपका कर्मचारी सूची में लिखता है, वैसा ही लिखें",
    "adati.nameHinglishHelp": "अपने आप भर जाता है। आप बदलेंगे तो हम फिर नहीं बदलेंगे।",
    "adati.autoFilled": "स्वतः", "adati.edited": "आपने बदला",
    "adati.resetAuto": "स्वतः वर्तनी लगाएँ",
    "adati.village": "गाँव", "adati.phone": "फ़ोन",
    "adati.accountNo": "खाता नं", "adati.ifsc": "IFSC",
    "adati.openingBalance": "प्रारंभिक शेष", "adati.notes": "टिप्पणी",
    "adati.aliases": "ज्ञात वर्तनियाँ", "adati.aliasCount": "वर्तनियाँ सीखीं",
    "adati.aliasHelp": "OCR जाँच में की गई हर सुधार यहाँ याद रह जाती है, ताकि अगली बार वही गलत पढ़ाई अपने आप सही हो जाए।",
    "adati.aliasAdd": "वर्तनी जोड़ें", "adati.aliasHits": "बार मिला",
    "adati.aliasSourceCanonical": "मुख्य नाम", "adati.aliasSourceCorrection": "सुधार",
    "adati.aliasSourceRename": "पुराना नाम", "adati.aliasSourceOcr": "OCR से",
    "adati.empty": "अभी कोई आढ़ती नहीं", "adati.emptySub": "अपनी दैनिक सूची के नाम जोड़ें, या स्कैन की गई शीट से लें।",
    "adati.regenerate": "स्वतः वर्तनी दोबारा बनाएँ",
    "adati.regenerateDone": "{total} में से {n} बदले। आपके बदले नाम जैसे थे वैसे रहे।",
    "adati.searchPlaceholder": "नाम, गाँव या फ़ोन से खोजें",
    "adati.deactivated": "इस आढ़ती की पर्चियाँ हैं, इसलिए हटाने के बजाय निष्क्रिय कर दिया।",
    "adati.count": "{n} आढ़ती",

    "merchant.title": "मिल व व्यापारी", "merchant.sub": "जिनके लिए आप लोड करते हैं, और उनकी शर्तें",
    "merchant.add": "मिल जोड़ें", "merchant.edit": "मिल बदलें",
    "merchant.code": "छोटा कोड", "merchant.codeHelp": "शीट के शीर्ष पर आता है, जैसे GRM या LB",
    "merchant.name": "मिल का नाम", "merchant.nameHi": "मिल का नाम हिन्दी में",
    "merchant.contactPerson": "संपर्क व्यक्ति", "merchant.charges": "शर्तें व कटौतियाँ",
    "merchant.chargesSub": "कच्चे पर्चे का हर अंक इन्हीं से बनता है",
    "merchant.weights": "वज़न व बारदाना",
    "merchant.katauti": "खरीद पर कटौती",
    "merchant.katautiHelp": "दैनिक सूची में घटती है। आपकी शीट की 45 पंक्तियों से जाँचा: 1 किलो प्रति क्विंटल, कुल वज़न को निकटतम क्विंटल पर गोल करके।",
    "merchant.katautiMode.per_quintal_rounded": "प्रति क्विंटल, गोल किया",
    "merchant.katautiMode.per_quintal_exact": "प्रति क्विंटल, सटीक",
    "merchant.katautiMode.none": "कटौती नहीं",
    "merchant.millBardana": "मिल पर बारदाना", "merchant.millBardanaHelp": "यह मिल खाली बोरे का वज़न कितना मानती है। आपके 20-09 पर्चे से 0.57 किलो निकलता है।",
    "merchant.adat": "कच्ची आढ़त", "merchant.labour1": "लेबर", "merchant.labour2": "लेबर (दूसरा)",
    "merchant.sutli": "सुतली", "merchant.gaushala": "गौशाला", "merchant.mandiTax": "मंडी टैक्स",
    "merchant.commission": "कमीशन", "merchant.gatePass": "गेट पास",
    "merchant.extraCharges": "अन्य कटौतियाँ", "merchant.extraAdd": "कटौती जोड़ें",
    "merchant.dara": "दारा", "merchant.advance": "एडवांस", "merchant.rounding": "महायोग की गोलाई",
    "merchant.parchaLayout": "पर्चे की बनावट",
    "merchant.chargedOn": "किस पर लगे", "merchant.base.amount": "केवल माल मूल्य",
    "merchant.base.amount_plus_adat": "माल मूल्य + आढ़त",
    "merchant.base.total_before_charge": "चालू योग",
    "merchant.weightBase.gross": "कुल वज़न (धर्म कांटा)", "merchant.weightBase.net": "शुद्ध वज़न",
    "merchant.daraMode.none": "नहीं लगता", "merchant.daraMode.per_bag": "प्रति बोरा",
    "merchant.daraMode.per_qtl": "प्रति क्विंटल", "merchant.daraMode.pct": "प्रतिशत",
    "merchant.daraMode.manual": "हर लोड पर डालें",
    "merchant.daraInTotal": "दारा को महायोग में जोड़ें",
    "merchant.daraInTotalHelp": "आपके नमूने वाले पर्चे में दारा छपता है पर महायोग में नहीं जुड़ता।",
    "merchant.advanceTreatment": "पर्चे पर एडवांस",
    "merchant.advance.add": "योग में जोड़ें", "merchant.advance.subtract": "योग से घटाएँ",
    "merchant.advance.exclude": "न दिखाएँ",
    "merchant.advanceHelp": "आपका 20-09 का पर्चा इसे जोड़ता है — भाड़ा जो आपने दिया और मिल से वसूलते हैं।",
    "merchant.rounding.none": "गोलाई नहीं", "merchant.rounding.nearest_rupee": "निकटतम रुपया",
    "merchant.rounding.up_rupee": "ऊपर का रुपया", "merchant.rounding.nearest_ten": "निकटतम दस रुपये",
    "merchant.preview": "तुरंत झलक", "merchant.previewSub": "इन शर्तों पर एक नमूना लोड",
    "merchant.previewGross": "कुल", "merchant.previewBags": "बोरे", "merchant.previewRate": "दर",
    "merchant.previewNet": "शुद्ध", "merchant.previewAdvance": "एडवांस", "merchant.previewDara": "दारा",
    "merchant.empty": "अभी कोई मिल नहीं", "merchant.emptySub": "जिन मिलों के लिए लोड करते हैं उन्हें उनकी कटौतियों के साथ जोड़ें।",
    "merchant.deactivated": "इस मिल के लोड हैं, इसलिए हटाने के बजाय निष्क्रिय कर दिया।",
    "merchant.enabled": "लगता है", "merchant.disabled": "नहीं लगता",
    "merchant.paymentTerms": "भुगतान अवधि (दिन)",
    "merchant.notInGrandTotal": "महायोग में नहीं",

    "jins.title": "जिंस", "jins.sub": "जो किस्में आप खरीदते-बेचते हैं",
    "jins.add": "जिंस जोड़ें", "jins.code": "कोड", "jins.name": "नाम",
    "jins.crop": "फ़सल", "jins.crop.paddy": "धान", "jins.crop.wheat": "गेहूँ",
    "jins.crop.maize": "मक्का", "jins.crop.other": "अन्य",

    "users.title": "उपयोगकर्ता", "users.sub": "कौन इसे चला सकता है, और क्या कर सकता है",
    "users.add": "उपयोगकर्ता जोड़ें", "users.edit": "उपयोगकर्ता बदलें", "users.role": "भूमिका",
    "users.setPin": "पिन तय करें", "users.resetPin": "पिन रीसेट करें", "users.unlock": "खोलें",
    "users.locked": "बंद", "users.lockedUntil": "{min} मिनट के लिए बंद",
    "users.owner": "स्वामी", "users.overrides": "अतिरिक्त अनुमतियाँ",
    "users.overridesSub": "भूमिका के ऊपर। मनाही हमेशा भारी पड़ती है।",
    "users.effectivePerms": "{n} अनुमतियाँ",
    "users.lastOwner": "यही एकमात्र स्वामी है। पहले किसी और को स्वामी बनाएँ।",
    "users.you": "आप",

    "roles.title": "भूमिका व अनुमतियाँ", "roles.sub": "हर भूमिका ठीक क्या कर सकती है",
    "roles.add": "भूमिका जोड़ें", "roles.key": "कुंजी", "roles.label": "नाम",
    "roles.builtIn": "अंतर्निहित", "roles.userCount": "{n} उपयोगकर्ता",
    "roles.ownerLocked": "स्वामी भूमिका के पास सारी अनुमतियाँ हमेशा रहती हैं।",
    "roles.selectAll": "सब चुनें", "roles.clearAll": "सब हटाएँ",
    "roles.permCount": "{total} में से {n}",

    "audit.title": "ऑडिट", "audit.sub": "हर बदलाव, किसने किया और पहले क्या था",
    "audit.filterEntity": "प्रकार", "audit.filterUser": "उपयोगकर्ता",
    "audit.filterAction": "क्रिया", "audit.loadMore": "पुराने देखें",
    "audit.empty": "अभी कुछ दर्ज नहीं", "audit.changed": "बदला",
    "audit.before": "पहले", "audit.after": "बाद में", "audit.noChange": "कोई खाना नहीं बदला",
    "audit.searchPlaceholder": "नाम, उपयोगकर्ता या क्रिया से खोजें",
    "audit.readOnly": "यह रिकॉर्ड कोई भी बदल या हटा नहीं सकता।",

    "dash.title": "डैशबोर्ड", "dash.comingSoon": "अगले चरण में बन रहा है",
    "dash.setupChecklist": "सेटअप पूरा करें", "dash.setupSub": "दैनिक सूची शुरू करने से पहले कुछ बातें भर लें",
    "dash.stepBusiness": "व्यापार का पता व लाइसेंस", "dash.stepMills": "मिल जोड़ें",
    "dash.stepSuppliers": "आढ़ती जोड़ें", "dash.stepUsers": "कर्मचारी जोड़ें",
    "dash.stepDone": "हो गया", "dash.stepTodo": "बाकी है",
    "dash.suppliers": "आढ़ती", "dash.mills": "मिल", "dash.commodities": "जिंस", "dash.staff": "कर्मचारी",

    "daily.title": "दैनिक सूची", "daily.sub": "हर आढ़ती पर्ची की एक पंक्ति",
    "daily.date": "दिनांक", "daily.today": "आज", "daily.prevDay": "पिछला दिन", "daily.nextDay": "अगला दिन",
    "daily.mill": "मिल", "daily.jins": "जिंस", "daily.allMills": "सभी मिल", "daily.noMill": "मिल तय नहीं",
    "daily.sheetHeader": "शीट शीर्ष", "daily.sheetHeaderSub": "आपकी कागज़ी शीट के ऊपर जैसा है",
    "daily.rst": "कांटा पर्ची (RST)", "daily.rstPlaceholder": "पर्ची नं", "daily.rstRepeated": "यह पर्ची नं आज एक से ज़्यादा बार है", "daily.supplier": "आढ़ती नाम", "daily.gross": "धर्म कांटा",
    "daily.bags": "कटौती", "daily.katautiWt": "कटौती वज़न", "daily.net": "शुद्ध वज़न",
    "daily.rate": "दर", "daily.amount": "राशि",
    "daily.newRow": "नई पंक्ति", "daily.addRow": "पंक्ति जोड़ें", "daily.saveRow": "पंक्ति सहेजें",
    "daily.totals": "कुल", "daily.rowCount": "{n} पंक्तियाँ", "daily.weightedAvg": "भारित औसत दर",
    "daily.enterToSave": "सहेजने के लिए Enter", "daily.escToCancel": "रद्द करने के लिए Esc",
    "daily.keyboardHelp": "लिखें और Enter दबाकर आगे बढ़ें। दर पर Enter दबाने से पंक्ति सहेज कर अगली शुरू होगी।",
    "daily.searchSupplier": "नाम हिन्दी या अंग्रेज़ी में लिखें",
    "daily.noSupplierFound": "कोई आढ़ती नहीं मिला", "daily.createSupplier": "\"{name}\" को नया आढ़ती बनाएँ",
    "daily.duplicateRst": "RST {rst} इस दिनांक पर पहले से है",
    "daily.lastRate": "पिछली दर", "daily.lastRateOn": "{date} को",
    "daily.onLoad": "लोड पर", "daily.lockedRow": "यह पर्ची लोड पर है, इसलिए बदली नहीं जा सकती",
    "daily.mismatchRows": "{n} पंक्तियों का जोड़ नहीं मिलता", "daily.recompute": "दिन दोबारा जोड़ें",
    "daily.recomputeDone": "{scanned} पंक्तियाँ जाँची, {changed} सुधारी।",
    "daily.empty": "इस दिनांक पर कुछ दर्ज नहीं",
    "daily.emptySub": "नीचे की पंक्ति में लिखना शुरू करें, या शीट स्कैन करें।",
    "daily.reassign": "मिल बदलें", "daily.selectedRows": "{n} चुनी", "daily.selectAllN": "सभी {n} चुनें",
    "daily.fromScan": "जिस स्कैन से यह पंक्ति आई, वह खोलें",
    "daily.netAuto": "शुद्ध वज़न गणना से आता है, हाथ से नहीं",
    "daily.confirmDeleteRow": "RST {rst} हटाएँ?",
    "daily.sheetTotal": "आपकी शीट का कुल", "daily.sheetTotalSub": "कागज़ पर नीचे जो लिखा है वह डालें, मिलान के लिए",
    "daily.matches": "मिल गया", "daily.differsBy": "{amount} का अंतर",
    "daily.perBag": "{kg} किलो प्रति क्विंटल",
    "daily.katautiAuto": "कटौती कुल वज़न से बनती है — शीट अलग हो तभी बदलें",
    "daily.katautiEdited": "बदली हुई",
    "daily.needMill": "पहले शीट शीर्ष से मिल चुनें",
    "daily.needSupplier": "आढ़ती चुनें", "daily.needGross": "धर्म कांटा वज़न डालें",
    "daily.rateLocked": "आपको दर तय करने की अनुमति नहीं है",
    "daily.ratePending": "दर तय नहीं", "daily.ratePendingRows": "{n} पंक्तियों की दर अभी तय नहीं",
    "daily.ratePendingSub": "वे भारित औसत से बाहर रखी गई हैं, क्योंकि वही औसत पर्चे की दर बनता है।",
    "daily.bagWarning": "बोरों की गिनती जाँचें", "daily.bagWarningRows": "{n} पंक्तियों में प्रति बोरा वज़न असामान्य है",
    "daily.bagWarningSub": "एक बोरे में आमतौर पर 35 से 45 किलो आता है। इनमें बहुत अलग निकल रहा है।",
    "daily.perBagAvg": "{kg} किलो प्रति बोरा", "daily.pricedNet": "दर वाला शुद्ध वज़न",
    "settings.numbers": "अंक व मुद्रा", "settings.numbersSub": "पूरे ऐप में हर अंक कैसे दिखे",
    "settings.numberFormat": "अंक समूहन",
    "settings.format.indian": "भारतीय — 10,81,909.36", "settings.format.international": "अंतरराष्ट्रीय — 1,081,909.36",
    "settings.format.plain": "कुछ नहीं — 1081909.36",
    "settings.showSymbol": "मुद्रा चिन्ह दिखाएँ", "settings.showSymbolSub": "हर राशि से पहले चिन्ह लगाता है",
    "settings.currencySymbol": "मुद्रा चिन्ह", "settings.symbolSpacing": "चिन्ह के बाद जगह",
    "settings.moneyDecimals": "राशि में पैसे", "settings.weightDecimals": "वज़न में दशमलव",
    "settings.rateDecimals": "दर में दशमलव", "settings.negativeStyle": "ऋणात्मक राशि",
    "settings.negative.minus": "ऋण चिन्ह — -21,213.91", "settings.negative.brackets": "कोष्ठक — (21,213.91)",
    "settings.showWordAmount": "बड़े योग के साथ लाख / करोड़ दिखाएँ",
    "settings.weightUnitLabel": "वज़न इकाई", "settings.defaultKatauti": "डिफ़ॉल्ट कटौती प्रति बोरा",
    "settings.defaultKatautiSub": "मिल न चुनी हो तो दैनिक सूची में यही लगेगी। आपकी शीट में 1 किलो है।",
    "settings.preview": "झलक", "settings.decimals0": "कुछ नहीं", "settings.decimals2": "दो", "settings.decimals3": "तीन",
    "settings.gemini": "Gemini API कुंजी", "settings.geminiSub": "स्कैन की गई शीट पढ़ने के लिए",
    "settings.apiKey": "API कुंजी", "settings.apiKeyHelp": "aistudio.google.com/apikey से। यह \"AIza\" से शुरू होती है। एन्क्रिप्टेड रखी जाती है; सहेजने के बाद दोबारा नहीं दिखेगी।",
    "settings.copyKeyFrom": "{name} से कुंजी लाएँ", "settings.copyKeyDone": "कुंजी आ गई",
    "settings.apiKeySet": "कुंजी सहेजी गई", "settings.apiKeyNone": "अभी कोई कुंजी नहीं",
    "settings.apiKeyUnreadable": "कुंजी रखी है पर पढ़ी नहीं जा सकी। दोबारा डालें।",
    "settings.replaceKey": "कुंजी बदलें", "settings.removeKey": "कुंजी हटाएँ",
    "settings.testKey": "जाँचें", "settings.testOk": "चल रही है — {ms} ms में जवाब",
    "settings.testFail": "विफल", "settings.model": "मॉडल", "settings.fallbackModel": "वैकल्पिक मॉडल",
    "settings.fallbackModelSub": "पहली बार पढ़ाई कमज़ोर हो तो इस मॉडल पर दोबारा कोशिश",
    "settings.fallbackBelow": "इस भरोसे से नीचे दोबारा कोशिश",
    "dlp.title": "दैनिक सूची सेटिंग", "dlp.sub": "सिर्फ़ इसी स्क्रीन पर लागू",
    "dlp.newRow": "खाली पंक्ति", "dlp.newRow.top": "सबसे ऊपर", "dlp.newRow.bottom": "सबसे नीचे",
    "dlp.sortOrder": "पंक्तियों का क्रम", "dlp.sort.entry": "जैसे डाली गईं", "dlp.sort.rstAsc": "RST नं, छोटे से बड़े",
    "dlp.sort.rstDesc": "RST नं, बड़े से छोटे", "dlp.sort.newestFirst": "नई पहले",
    "dlp.density": "पंक्ति की ऊँचाई", "dlp.density.compact": "सघन", "dlp.density.normal": "सामान्य",
    "dlp.uiColumns": "स्क्रीन पर खाने", "dlp.exportColumns": "डाउनलोड में खाने",
    "dlp.locked": "हमेशा दिखेगा", "dlp.carryRate": "अगली पंक्ति में वही दर ले जाएँ",
    "dlp.showRunningTotal": "चालू जोड़ दिखाएँ",
    "dlp.scope": "इसे कहाँ रखें", "dlp.scopeSession": "सिर्फ़ इस ब्राउज़र में",
    "dlp.scopeUser": "मेरे लिए हर जगह सहेजें", "dlp.scopeSessionSub": "ब्राउज़र साफ़ करने पर चला जाएगा। सर्वर पर कुछ नहीं जाता।",
    "dlp.scopeUserSub": "किसी भी मशीन पर आपके लॉगिन के साथ रहेगा।",
    "dlp.sessionActive": "ब्राउज़र-वाली बनावट चल रही है", "dlp.clearSession": "ब्राउज़र-वाली बनावट हटाएँ",
    "dlp.reset": "डिफ़ॉल्ट पर लौटें", "dlp.applySession": "अभी के लिए लगाएँ", "dlp.applyUser": "मेरे लिए सहेजें",
    "dlp.rounding": "कटौती की गोलाई", "dlp.rounding.half_up": "आधा ऊपर — 32.50 से 33 (स्वामी के पक्ष में)",
    "dlp.rounding.up": "हमेशा ऊपर — 32.10 से 33", "dlp.rounding.down": "हमेशा नीचे — 32.90 से 32",
    "dlp.rounding.half_even": "आधा सम की ओर — 32.50 से 32",
    "dlp.roundingSub": "आधा-ऊपर आपकी शीट की सभी 45 पंक्तियों से मिला, और हर .50 ऊपर जाता है।",
    "scan.title": "स्कैन व OCR", "scan.sub": "हाथ से लिखी शीट पढ़ें, जाँचें, फिर दैनिक सूची में डालें",
    "scan.upload": "शीट अपलोड करें", "scan.uploadSub": "अपनी हाथ से लिखी दैनिक सूची की फ़ोटो या स्कैन — वही पन्ना जिसमें आढ़ती नाम, RST नं, धर्म कांटा, कटौती, शुद्ध वज़न और दर हैं। JPG, JPEG, PNG, WEBP, HEIC या PDF। एक साथ कई पन्ने चुनें; दो पन्नों की शीट एक ही सूची बनती है।",
    "scan.dropHere": "स्कैन यहाँ छोड़ें, या चुनने के लिए क्लिक करें (एक साथ कई चल जाएँगे)",
    "scan.chooseFiles": "फ़ाइल चुनें",
    "scan.noFilesPicked": "कोई फ़ाइल नहीं चुनी गई। दोबारा कोशिश करें, या स्कैन को बॉक्स पर खींचकर छोड़ें।",
    "scan.uploading": "{n} पन्ने भेजे जा रहे हैं…", "scan.pages": "{n} पन्ने", "scan.page": "पन्ना {n}",
    "scan.read": "शीट पढ़ें", "scan.reading": "पढ़ रहे हैं…", "scan.rereadWith": "दोबारा पढ़ें",
    "scan.status.uploaded": "अभी पढ़ी नहीं", "scan.status.reading": "पढ़ी जा रही है",
    "scan.status.review": "जाँच बाकी", "scan.status.committed": "दैनिक सूची में जुड़ गई",
    "scan.status.failed": "विफल",
    "scan.filterStatus": "स्थिति", "scan.filterFrom": "से", "scan.filterTo": "तक",
    "scan.filterMill": "मिल", "scan.clearFilters": "फ़िल्टर हटाएँ",
    "scan.empty": "अभी कोई स्कैन नहीं", "scan.emptySub": "अपनी दैनिक शीट स्कैन या फ़ोटो करके यहाँ डालें।",
    "scan.noKey": "स्कैन से पहले सेटिंग में Gemini API कुंजी डालें",
    "scan.review": "जाँच",
    "scan.showScan": "स्कैन दिखाएँ", "scan.hideScan": "स्कैन छिपाएँ",
    "scan.conf": "पढ़ाई", "scan.issues": "जाँच", "scan.rowNo": "#",
    "scan.extracted": "निकाली गई पंक्तियाँ — स्वीकारने से पहले कुछ भी बदलें",
    "scan.notFound": "यह स्कैन इस व्यापार में नहीं है",
    "scan.notFoundSub": "स्कैन उसी व्यापार का होता है जिसमें अपलोड हुआ था। व्यापार बदलें, या दूसरा स्कैन चुनें।",
    "scan.findIt": "कहाँ है, पता करें", "scan.foundInBusiness": "यह {name} का है।",
    "scan.switchAndOpen": "{name} पर जाकर खोलें",
    "scan.createMissing": "{n} नए आढ़ती जोड़ें",
    "scan.suppliersCreated": "{created} आढ़ती जुड़े, {linked} पंक्तियाँ भर गईं।",
    "scan.rowsWord": "पंक्तियाँ", "scan.needSuppliers": "{n} पंक्तियों में आढ़ती चुनें",
    "scan.reviewSub": "हर पंक्ति कागज़ से मिलाएँ, फिर दैनिक सूची में डालें",
    "scan.summary.total": "पढ़ी पंक्तियाँ", "scan.summary.clean": "साफ़", "scan.summary.warnings": "जाँचने योग्य",
    "scan.summary.blocking": "ठीक करना ज़रूरी", "scan.summary.excluded": "छोड़ी गईं",
    "scan.summary.netAgree": "शुद्ध वज़न कागज़ से मिला", "scan.summary.names": "नाम मिले",
    "scan.summary.confidence": "पढ़ने का भरोसा",
    "scan.netAgreeHelp": "वे पंक्तियाँ जहाँ कागज़ पर लिखा शुद्ध वज़न हमारी गणना से मिलता है। ये लगभग निश्चित रूप से सही पढ़ी गई हैं।",
    "scan.commit": "दैनिक सूची में डालें", "scan.committing": "डाल रहे हैं…",
    "scan.commitBlocked": "पहले {n} पंक्तियाँ ठीक करें", "scan.committed": "{date} में {n} पंक्तियाँ जुड़ीं",
    "scan.learned": "{n} नई वर्तनियाँ सीखीं",
    "scan.openDaily": "दैनिक सूची खोलें", "scan.exclude": "यह पंक्ति छोड़ें", "scan.include": "वापस लाएँ",
    "scan.struck": "कागज़ पर काटी गई है", "scan.pickName": "आढ़ती चुनें",
    "scan.matchedBy.alias": "ज्ञात वर्तनी", "scan.matchedBy.normkey": "मिलती-जुलती वर्तनी", "scan.matchedBy.fuzzy": "समान", "scan.pickedByYou": "आपने चुना",
    "scan.matchedBy.model": "सूची से पढ़ा", "scan.clickToChange": "आढ़ती बदलने के लिए क्लिक करें",
    "scan.whyGross": "कागज़ पर शुद्ध वज़न {net} है, जो इस धर्म कांटे से मेल नहीं खाता। धर्म कांटा जाँचें, या स्वीकारने के लिए तारा दबाएँ।",
    "scan.readingPage": "पन्ना {n} / {total} पढ़ा जा रहा है…", "scan.readingMore": "हर पन्ना पढ़ते ही उसकी पंक्तियाँ यहाँ आती जाएँगी।",
    "scan.dragToResize": "आकार बदलने के लिए खींचें",
    "scan.fixRedStars": "पहले {n} लाल खाने ठीक करें",
    "scan.slipCol": "कांटा पर्ची (RST)",
    "scan.fix.rstMissing": "कांटा पर्ची नं लिखें",
    "scan.fix.rstExists": "इस तारीख़ की दैनिक सूची में पहले से है — यह पंक्ति हटाएँ",
    "scan.fix.pickName": "आढ़ती चुनें",
    "scan.fix.grossMissing": "धर्म कांटा वज़न लिखें",
    "scan.fix.netNonPositive": "वज़न बहुत कम — दशमलव जाँचें",
    "scan.orderTitle": "पन्नों का क्रम तय करें", "scan.orderSub": "सब एक ही सूची की तरह पढ़े जाएँगे, ऊपर से नीचे, पहले पन्ना 1",
    "scan.orderHint": "पन्ना खिसकाने के लिए तीर दबाएँ। पन्ना 1 वह है जिस पर शीट का शीर्ष है।",
    "scan.moveUp": "पहले", "scan.moveDown": "बाद में", "scan.readInOrder": "इसी क्रम में पढ़ें",
    "scan.rowsOnPage": "{n} पंक्तियाँ",
    "scan.ocrSaid": "पढ़ा गया", "scan.wasRead": "पढ़ा गया", "scan.restoreRead": "शीट से जो पढ़ा गया था वही वापस लाएँ", "scan.derived": "गणना", "scan.sheetSaid": "कागज़ पर",
    "scan.needDate": "शीट की तारीख़ डालें", "scan.needJins": "जिंस चुनें",
    "scan.header": "शीट शीर्ष", "scan.headerRead": "पढ़ने वाले ने देखा",
    "scan.zoomIn": "बड़ा करें", "scan.zoomOut": "छोटा करें", "scan.fit": "फ़िट",
    "scan.deleteScan": "यह स्कैन हटाएँ", "scan.confirmDelete": "यह स्कैन और इसकी तस्वीरें हटाएँ?",
    "scan.rowsOnly": "सिर्फ़ दिखाएँ", "scan.rowsAll": "सभी पंक्तियाँ", "scan.rowsIssues": "जिनमें दिक्कत है",
    "scan.rowsBlocking": "जो ठीक करनी हैं", "scan.rowsClean": "साफ़ पंक्तियाँ",
    "scan.failedTitle": "शीट पढ़ी नहीं जा सकी", "scan.tryAgain": "फिर कोशिश करें",
    "scan.costNote": "टोकन: {in} अंदर, {out} बाहर",
    "issue.rst_missing": "RST नंबर पढ़ा नहीं जा सका",
    "issue.rst_exists": "RST {rst} इस तारीख़ पर पहले से दर्ज है",
    "issue.rst_dupe": "RST {rst} इसी शीट पर दो बार है",
    "issue.name_unresolved": "\"{name}\" से कोई आढ़ती नहीं मिला",
    "issue.name_missing": "आढ़ती का नाम पढ़ा नहीं जा सका",
    "issue.name_fuzzy": "\"{name}\" से मिलता-जुलता नाम लिया गया — जाँच लें",
    "issue.gross_missing": "धर्म कांटा वज़न पढ़ा नहीं जा सका",
    "issue.net_nonpositive": "शुद्ध वज़न शून्य या उससे कम निकल रहा है",
    "issue.gross_large": "एक पर्ची के लिए वज़न बहुत ज़्यादा लग रहा है",
    "issue.gross_small": "वज़न एक क्विंटल से कम है — दशमलव जाँचें",
    "issue.net_mismatch": "कागज़ का शुद्ध वज़न गणना से {diff} क्विंटल अलग है",
    "issue.katauti_mismatch": "कागज़ पर कटौती {sheet} है, गणना {calculated}",
    "issue.rate_missing": "दर पढ़ी नहीं जा सकी — बाद में भर सकते हैं",
    "issue.rate_range": "दर सामान्य सीमा से बाहर है — जाँच लें",
    "issue.low_confidence": "पढ़ने वाले को इस पंक्ति पर भरोसा कम था",
    "err.noPermission": "आपको इसकी अनुमति नहीं है",
    "err.noPermissionSub": "किसी स्वामी से {perm} अनुमति माँगें।",
    "err.offline": "सर्वर से संपर्क नहीं हो रहा",
    "err.offlineSub": "स्थानीय सेवा रुक गई होगी। जाँचें कि वह चल रही है, फिर दोबारा कोशिश करें।",
    "err.crashed": "इस स्क्रीन में दिक्कत आ गई", "err.crashedSub": "कुछ खोया नहीं है। स्क्रीन दोबारा लोड करें, या डैशबोर्ड पर लौटें।",
    "err.reload": "दोबारा लोड करें",
  },
} as const;

export type Lang = keyof typeof STRINGS;
export type StringKey = keyof typeof STRINGS["en"];
