/** Every visible string lives here in both languages. */
export const STRINGS = {
  en: {
    "app.name": "Mandi Mitra",
    "app.tagline": "Daily list, stock and kaccha parcha",

    "common.save": "Save", "common.saving": "Saving…", "common.cancel": "Cancel",
    "common.add": "Add", "common.edit": "Edit", "common.delete": "Delete",
    "common.search": "Search", "common.close": "Close", "common.back": "Back",
    "common.next": "Next", "common.done": "Done", "common.retry": "Retry",
    "common.yes": "Yes", "common.no": "No", "common.optional": "optional",
    "common.required": "required", "common.active": "Active", "common.inactive": "Inactive",
    "common.showInactive": "Show inactive", "common.noResults": "Nothing found",
    "common.loading": "Loading…", "common.all": "All", "common.none": "None",
    "common.confirmDelete": "Delete this?", "common.deleted": "Deleted",
    "common.saved": "Saved", "common.copy": "Copy", "common.copied": "Copied",
    "common.hindi": "Hindi", "common.hinglish": "Hinglish", "common.english": "English",
    "common.language": "Language", "common.theme": "Theme",
    "common.themeLight": "Light", "common.themeDark": "Dark", "common.themeSystem": "System",
    "common.perBag": "per bag", "common.perQtl": "per quintal", "common.perTruck": "per truck",
    "common.quintal": "qtl", "common.bags": "bags", "common.rupees": "Rs",
    "common.somethingWrong": "Something went wrong",

    "nav.dashboard": "Dashboard", "nav.dailyList": "Daily list", "nav.scan": "Scan & OCR",
    "nav.loads": "Loads", "nav.parcha": "Kaccha parcha", "nav.stock": "Stock",
    "nav.suppliers": "Suppliers", "nav.mills": "Mills", "nav.commodities": "Commodities",
    "nav.ledger": "Ledger", "nav.payments": "Payments", "nav.users": "Users",
    "nav.roles": "Roles", "nav.audit": "Audit trail", "nav.settings": "Settings",
    "nav.masters": "Masters", "nav.operations": "Operations", "nav.accounts": "Accounts",
    "nav.admin": "Administration",

    "auth.welcome": "Welcome", "auth.setupTitle": "Set up Mandi Mitra",
    "auth.setupSub": "This runs once. You can change everything later.",
    "auth.yourName": "Your name", "auth.yourNameHi": "Your name in Hindi",
    "auth.phone": "Phone", "auth.pin": "PIN", "auth.pinAgain": "Confirm PIN",
    "auth.pinHelp": "4 to 6 digits. You will use this to sign in.",
    "auth.pinMismatch": "The two PINs do not match",
    "auth.businessName": "Business name", "auth.businessNameHi": "Business name in Hindi",
    "auth.shortCode": "Short code", "auth.shortCodeHelp": "Shows on the parcha, e.g. VLDM",
    "auth.createAccount": "Create account", "auth.signIn": "Sign in",
    "auth.whoAreYou": "Who is signing in?", "auth.enterPin": "Enter PIN",
    "auth.wrongPin": "Wrong PIN", "auth.signOut": "Sign out",
    "auth.changePin": "Change PIN", "auth.currentPin": "Current PIN", "auth.newPin": "New PIN",
    "auth.switchUser": "Switch user",

    "biz.switch": "Switch business", "biz.add": "Add business",
    "biz.addSub": "A second firm, e.g. V C Enterprise. Suppliers, mills and stock stay separate.",
    "biz.profile": "Business profile", "biz.address": "Address",
    "biz.addressLine1": "Address line 1", "biz.addressLine2": "Address line 2",
    "biz.city": "City", "biz.district": "District", "biz.state": "State",
    "biz.pincode": "PIN code", "biz.gstin": "GSTIN", "biz.mandiLicense": "Mandi licence no",
    "biz.panNo": "PAN", "biz.current": "Current business",

    "adati.title": "Suppliers", "adati.sub": "The small businesses you buy from",
    "adati.add": "Add supplier", "adati.edit": "Edit supplier",
    "adati.nameHi": "Name in Hindi", "adati.nameHinglish": "Name in Hinglish",
    "adati.nameHiHelp": "Write it exactly as your employee writes it on the sheet",
    "adati.nameHinglishHelp": "Filled in automatically. Edit it and we stop changing it.",
    "adati.autoFilled": "auto", "adati.edited": "edited by you",
    "adati.resetAuto": "Use auto spelling",
    "adati.village": "Village", "adati.phone": "Phone",
    "adati.accountNo": "Account no", "adati.ifsc": "IFSC",
    "adati.openingBalance": "Opening balance", "adati.notes": "Notes",
    "adati.aliases": "Known spellings", "adati.aliasCount": "spellings learnt",
    "adati.aliasHelp": "Every correction the OCR review screen makes is remembered here, so the same misreading resolves by itself next time.",
    "adati.aliasAdd": "Add a spelling", "adati.aliasHits": "matched",
    "adati.aliasSourceCanonical": "main name", "adati.aliasSourceCorrection": "correction",
    "adati.aliasSourceRename": "old name", "adati.aliasSourceOcr": "from OCR",
    "adati.empty": "No suppliers yet", "adati.emptySub": "Add the names from your daily list, or import them from a scanned sheet.",
    "adati.regenerate": "Redo auto spellings",
    "adati.regenerateDone": "Updated {n} of {total}. Names you edited were left alone.",
    "adati.searchPlaceholder": "Search by name, village or phone",
    "adati.deactivated": "This supplier has slips, so it was made inactive instead of deleted.",
    "adati.count": "{n} suppliers",

    "merchant.title": "Mills & merchants", "merchant.sub": "Who you load for, and the terms each one charges",
    "merchant.add": "Add mill", "merchant.edit": "Edit mill",
    "merchant.code": "Short code", "merchant.codeHelp": "Appears on the sheet header, e.g. GRM or LB",
    "merchant.name": "Mill name", "merchant.nameHi": "Mill name in Hindi",
    "merchant.contactPerson": "Contact person", "merchant.charges": "Charge terms",
    "merchant.chargesSub": "These drive every number on the kaccha parcha",
    "merchant.weights": "Weights & bardana",
    "merchant.katauti": "Katauti when buying", "merchant.katautiHelp": "Deducted per bag on your daily list. Your sheets use 1 kg per bag.",
    "merchant.millBardana": "Bardana at the mill", "merchant.millBardanaHelp": "How this mill weighs an empty bag. Your 20-09 parcha works out to 0.57 kg.",
    "merchant.adat": "Kacchi adat", "merchant.labour1": "Labour", "merchant.labour2": "Labour (second slab)",
    "merchant.sutli": "Sutli", "merchant.gaushala": "Gaushala", "merchant.mandiTax": "Mandi tax",
    "merchant.commission": "Commission", "merchant.gatePass": "Gate pass",
    "merchant.extraCharges": "Other charges", "merchant.extraAdd": "Add a charge",
    "merchant.dara": "Dara", "merchant.advance": "Advance", "merchant.rounding": "Grand total rounding",
    "merchant.parchaLayout": "Parcha layout",
    "merchant.chargedOn": "charged on", "merchant.base.amount": "Goods value only",
    "merchant.base.amount_plus_adat": "Goods value + adat",
    "merchant.base.total_before_charge": "Running total",
    "merchant.weightBase.gross": "Gross weight (dharam kanta)", "merchant.weightBase.net": "Net weight",
    "merchant.daraMode.none": "Not used", "merchant.daraMode.per_bag": "Per bag",
    "merchant.daraMode.per_qtl": "Per quintal", "merchant.daraMode.pct": "Percentage",
    "merchant.daraMode.manual": "Typed in per load",
    "merchant.daraInTotal": "Include dara in grand total",
    "merchant.daraInTotalHelp": "Your sample parcha prints dara but leaves it out of the grand total.",
    "merchant.advanceTreatment": "Advance on the parcha",
    "merchant.advance.add": "Added to the total", "merchant.advance.subtract": "Deducted from the total",
    "merchant.advance.exclude": "Not shown",
    "merchant.advanceHelp": "Your 20-09 parcha adds it — freight you paid and recover from the mill.",
    "merchant.rounding.none": "No rounding", "merchant.rounding.nearest_rupee": "Nearest rupee",
    "merchant.rounding.up_rupee": "Round up to rupee", "merchant.rounding.nearest_ten": "Nearest ten rupees",
    "merchant.preview": "Live preview", "merchant.previewSub": "A sample load run through these terms",
    "merchant.previewGross": "Gross", "merchant.previewBags": "Bags", "merchant.previewRate": "Rate",
    "merchant.previewNet": "Net", "merchant.previewAdvance": "Advance", "merchant.previewDara": "Dara",
    "merchant.empty": "No mills yet", "merchant.emptySub": "Add the mills you load for, with the charges each one applies.",
    "merchant.deactivated": "This mill has loads, so it was made inactive instead of deleted.",
    "merchant.enabled": "Applied", "merchant.disabled": "Not applied",
    "merchant.paymentTerms": "Payment terms (days)",
    "merchant.notInGrandTotal": "not in grand total",

    "jins.title": "Commodities", "jins.sub": "The varieties you trade",
    "jins.add": "Add commodity", "jins.code": "Code", "jins.name": "Name",
    "jins.crop": "Crop", "jins.crop.paddy": "Paddy", "jins.crop.wheat": "Wheat",
    "jins.crop.maize": "Maize", "jins.crop.other": "Other",

    "users.title": "Users", "users.sub": "Who can use this, and what they may do",
    "users.add": "Add user", "users.edit": "Edit user", "users.role": "Role",
    "users.setPin": "Set PIN", "users.resetPin": "Reset PIN", "users.unlock": "Unlock",
    "users.locked": "Locked", "users.lockedUntil": "Locked for {min} min",
    "users.owner": "Owner", "users.overrides": "Extra permissions",
    "users.overridesSub": "On top of the role. A deny always wins.",
    "users.effectivePerms": "{n} permissions",
    "users.lastOwner": "This is the only Owner. Make someone else an Owner first.",
    "users.you": "you",

    "roles.title": "Roles & permissions", "roles.sub": "Exactly what each role may do",
    "roles.add": "Add role", "roles.key": "Key", "roles.label": "Name",
    "roles.builtIn": "built-in", "roles.userCount": "{n} users",
    "roles.ownerLocked": "The Owner role always keeps every permission.",
    "roles.selectAll": "Select all", "roles.clearAll": "Clear all",
    "roles.permCount": "{n} of {total}",

    "audit.title": "Audit trail", "audit.sub": "Every change, who made it and what it was before",
    "audit.filterEntity": "Type", "audit.filterUser": "User", "audite.filterAction": "Action",
    "audit.filterAction": "Action", "audit.loadMore": "Load older",
    "audit.empty": "Nothing recorded yet", "audit.changed": "Changed",
    "audit.before": "Before", "audit.after": "After", "audit.noChange": "no field changed",
    "audit.searchPlaceholder": "Search by name, user or action",
    "audit.readOnly": "This log cannot be edited or deleted, by anyone.",

    "dash.title": "Dashboard", "dash.comingSoon": "Being built next",
    "dash.setupChecklist": "Finish setting up", "dash.setupSub": "A few things to fill in before the daily list is useful",
    "dash.stepBusiness": "Business address and licence", "dash.stepMills": "Add the mills you load for",
    "dash.stepSuppliers": "Add your suppliers", "dash.stepUsers": "Add your staff",
    "dash.stepDone": "Done", "dash.stepTodo": "To do",
    "dash.suppliers": "Suppliers", "dash.mills": "Mills", "dash.commodities": "Commodities", "dash.staff": "Staff",

    "err.noPermission": "You do not have permission for this",
    "err.noPermissionSub": "Ask an Owner to give you the {perm} permission.",
    "err.offline": "Cannot reach the server",
    "err.offlineSub": "The local service may have stopped. Check that it is running, then retry.",
  },

  hi: {
    "app.name": "मंडी मित्र",
    "app.tagline": "दैनिक सूची, स्टॉक और कच्चा पर्चा",

    "common.save": "सहेजें", "common.saving": "सहेज रहे हैं…", "common.cancel": "रद्द करें",
    "common.add": "जोड़ें", "common.edit": "बदलें", "common.delete": "हटाएँ",
    "common.search": "खोजें", "common.close": "बंद करें", "common.back": "पीछे",
    "common.next": "आगे", "common.done": "पूरा", "common.retry": "फिर कोशिश करें",
    "common.yes": "हाँ", "common.no": "नहीं", "common.optional": "वैकल्पिक",
    "common.required": "आवश्यक", "common.active": "सक्रिय", "common.inactive": "निष्क्रिय",
    "common.showInactive": "निष्क्रिय दिखाएँ", "common.noResults": "कुछ नहीं मिला",
    "common.loading": "लोड हो रहा है…", "common.all": "सभी", "common.none": "कोई नहीं",
    "common.confirmDelete": "इसे हटाएँ?", "common.deleted": "हटा दिया",
    "common.saved": "सहेज लिया", "common.copy": "कॉपी", "common.copied": "कॉपी हो गया",
    "common.hindi": "हिन्दी", "common.hinglish": "हिंग्लिश", "common.english": "अंग्रेज़ी",
    "common.language": "भाषा", "common.theme": "थीम",
    "common.themeLight": "उजला", "common.themeDark": "गहरा", "common.themeSystem": "सिस्टम",
    "common.perBag": "प्रति बोरा", "common.perQtl": "प्रति क्विंटल", "common.perTruck": "प्रति ट्रक",
    "common.quintal": "क्विं", "common.bags": "बोरे", "common.rupees": "रु",
    "common.somethingWrong": "कुछ गड़बड़ हो गई",

    "nav.dashboard": "डैशबोर्ड", "nav.dailyList": "दैनिक सूची", "nav.scan": "स्कैन व OCR",
    "nav.loads": "लोड", "nav.parcha": "कच्चा पर्चा", "nav.stock": "स्टॉक",
    "nav.suppliers": "आढ़ती", "nav.mills": "मिल", "nav.commodities": "जिंस",
    "nav.ledger": "खाता", "nav.payments": "भुगतान", "nav.users": "उपयोगकर्ता",
    "nav.roles": "भूमिका", "nav.audit": "ऑडिट", "nav.settings": "सेटिंग",
    "nav.masters": "मास्टर", "nav.operations": "कामकाज", "nav.accounts": "खाता",
    "nav.admin": "प्रशासन",

    "auth.welcome": "स्वागत है", "auth.setupTitle": "मंडी मित्र शुरू करें",
    "auth.setupSub": "यह एक बार होता है। सब कुछ बाद में बदल सकते हैं।",
    "auth.yourName": "आपका नाम", "auth.yourNameHi": "आपका नाम हिन्दी में",
    "auth.phone": "फ़ोन", "auth.pin": "पिन", "auth.pinAgain": "पिन दोबारा",
    "auth.pinHelp": "4 से 6 अंक। इससे आप लॉगिन करेंगे।",
    "auth.pinMismatch": "दोनों पिन एक जैसे नहीं हैं",
    "auth.businessName": "व्यापार का नाम", "auth.businessNameHi": "व्यापार का नाम हिन्दी में",
    "auth.shortCode": "छोटा कोड", "auth.shortCodeHelp": "पर्चे पर दिखेगा, जैसे VLDM",
    "auth.createAccount": "खाता बनाएँ", "auth.signIn": "लॉगिन",
    "auth.whoAreYou": "कौन लॉगिन कर रहा है?", "auth.enterPin": "पिन डालें",
    "auth.wrongPin": "पिन गलत है", "auth.signOut": "लॉगआउट",
    "auth.changePin": "पिन बदलें", "auth.currentPin": "वर्तमान पिन", "auth.newPin": "नया पिन",
    "auth.switchUser": "उपयोगकर्ता बदलें",

    "biz.switch": "व्यापार बदलें", "biz.add": "व्यापार जोड़ें",
    "biz.addSub": "दूसरी फर्म, जैसे V C Enterprise। आढ़ती, मिल और स्टॉक अलग रहेंगे।",
    "biz.profile": "व्यापार प्रोफ़ाइल", "biz.address": "पता",
    "biz.addressLine1": "पता पंक्ति 1", "biz.addressLine2": "पता पंक्ति 2",
    "biz.city": "शहर", "biz.district": "ज़िला", "biz.state": "राज्य",
    "biz.pincode": "पिन कोड", "biz.gstin": "GSTIN", "biz.mandiLicense": "मंडी लाइसेंस नं",
    "biz.panNo": "पैन", "biz.current": "वर्तमान व्यापार",

    "adati.title": "आढ़ती", "adati.sub": "जिनसे आप माल खरीदते हैं",
    "adati.add": "आढ़ती जोड़ें", "adati.edit": "आढ़ती बदलें",
    "adati.nameHi": "नाम हिन्दी में", "adati.nameHinglish": "नाम हिंग्लिश में",
    "adati.nameHiHelp": "जैसा आपका कर्मचारी सूची में लिखता है, वैसा ही लिखें",
    "adati.nameHinglishHelp": "अपने आप भर जाता है। आप बदलेंगे तो हम फिर नहीं बदलेंगे।",
    "adati.autoFilled": "स्वतः", "adati.edited": "आपने बदला",
    "adati.resetAuto": "स्वतः वर्तनी लगाएँ",
    "adati.village": "गाँव", "adati.phone": "फ़ोन",
    "adati.accountNo": "खाता नं", "adati.ifsc": "IFSC",
    "adati.openingBalance": "प्रारंभिक शेष", "adati.notes": "टिप्पणी",
    "adati.aliases": "ज्ञात वर्तनियाँ", "adati.aliasCount": "वर्तनियाँ सीखीं",
    "adati.aliasHelp": "OCR जाँच में की गई हर सुधार यहाँ याद रह जाती है, ताकि अगली बार वही गलत पढ़ाई अपने आप सही हो जाए।",
    "adati.aliasAdd": "वर्तनी जोड़ें", "adati.aliasHits": "बार मिला",
    "adati.aliasSourceCanonical": "मुख्य नाम", "adati.aliasSourceCorrection": "सुधार",
    "adati.aliasSourceRename": "पुराना नाम", "adati.aliasSourceOcr": "OCR से",
    "adati.empty": "अभी कोई आढ़ती नहीं", "adati.emptySub": "अपनी दैनिक सूची के नाम जोड़ें, या स्कैन की गई शीट से लें।",
    "adati.regenerate": "स्वतः वर्तनी दोबारा बनाएँ",
    "adati.regenerateDone": "{total} में से {n} बदले। आपके बदले नाम जैसे थे वैसे रहे।",
    "adati.searchPlaceholder": "नाम, गाँव या फ़ोन से खोजें",
    "adati.deactivated": "इस आढ़ती की पर्चियाँ हैं, इसलिए हटाने के बजाय निष्क्रिय कर दिया।",
    "adati.count": "{n} आढ़ती",

    "merchant.title": "मिल व व्यापारी", "merchant.sub": "जिनके लिए आप लोड करते हैं, और उनकी शर्तें",
    "merchant.add": "मिल जोड़ें", "merchant.edit": "मिल बदलें",
    "merchant.code": "छोटा कोड", "merchant.codeHelp": "शीट के शीर्ष पर आता है, जैसे GRM या LB",
    "merchant.name": "मिल का नाम", "merchant.nameHi": "मिल का नाम हिन्दी में",
    "merchant.contactPerson": "संपर्क व्यक्ति", "merchant.charges": "शर्तें व कटौतियाँ",
    "merchant.chargesSub": "कच्चे पर्चे का हर अंक इन्हीं से बनता है",
    "merchant.weights": "वज़न व बारदाना",
    "merchant.katauti": "खरीद पर कटौती", "merchant.katautiHelp": "दैनिक सूची में प्रति बोरा घटती है। आपकी शीट में 1 किलो प्रति बोरा है।",
    "merchant.millBardana": "मिल पर बारदाना", "merchant.millBardanaHelp": "यह मिल खाली बोरे का वज़न कितना मानती है। आपके 20-09 पर्चे से 0.57 किलो निकलता है।",
    "merchant.adat": "कच्ची आढ़त", "merchant.labour1": "लेबर", "merchant.labour2": "लेबर (दूसरा)",
    "merchant.sutli": "सुतली", "merchant.gaushala": "गौशाला", "merchant.mandiTax": "मंडी टैक्स",
    "merchant.commission": "कमीशन", "merchant.gatePass": "गेट पास",
    "merchant.extraCharges": "अन्य कटौतियाँ", "merchant.extraAdd": "कटौती जोड़ें",
    "merchant.dara": "दारा", "merchant.advance": "एडवांस", "merchant.rounding": "महायोग की गोलाई",
    "merchant.parchaLayout": "पर्चे की बनावट",
    "merchant.chargedOn": "किस पर लगे", "merchant.base.amount": "केवल माल मूल्य",
    "merchant.base.amount_plus_adat": "माल मूल्य + आढ़त",
    "merchant.base.total_before_charge": "चालू योग",
    "merchant.weightBase.gross": "कुल वज़न (धर्म कांटा)", "merchant.weightBase.net": "शुद्ध वज़न",
    "merchant.daraMode.none": "नहीं लगता", "merchant.daraMode.per_bag": "प्रति बोरा",
    "merchant.daraMode.per_qtl": "प्रति क्विंटल", "merchant.daraMode.pct": "प्रतिशत",
    "merchant.daraMode.manual": "हर लोड पर डालें",
    "merchant.daraInTotal": "दारा को महायोग में जोड़ें",
    "merchant.daraInTotalHelp": "आपके नमूने वाले पर्चे में दारा छपता है पर महायोग में नहीं जुड़ता।",
    "merchant.advanceTreatment": "पर्चे पर एडवांस",
    "merchant.advance.add": "योग में जोड़ें", "merchant.advance.subtract": "योग से घटाएँ",
    "merchant.advance.exclude": "न दिखाएँ",
    "merchant.advanceHelp": "आपका 20-09 का पर्चा इसे जोड़ता है — भाड़ा जो आपने दिया और मिल से वसूलते हैं।",
    "merchant.rounding.none": "गोलाई नहीं", "merchant.rounding.nearest_rupee": "निकटतम रुपया",
    "merchant.rounding.up_rupee": "ऊपर का रुपया", "merchant.rounding.nearest_ten": "निकटतम दस रुपये",
    "merchant.preview": "तुरंत झलक", "merchant.previewSub": "इन शर्तों पर एक नमूना लोड",
    "merchant.previewGross": "कुल", "merchant.previewBags": "बोरे", "merchant.previewRate": "दर",
    "merchant.previewNet": "शुद्ध", "merchant.previewAdvance": "एडवांस", "merchant.previewDara": "दारा",
    "merchant.empty": "अभी कोई मिल नहीं", "merchant.emptySub": "जिन मिलों के लिए लोड करते हैं उन्हें उनकी कटौतियों के साथ जोड़ें।",
    "merchant.deactivated": "इस मिल के लोड हैं, इसलिए हटाने के बजाय निष्क्रिय कर दिया।",
    "merchant.enabled": "लगता है", "merchant.disabled": "नहीं लगता",
    "merchant.paymentTerms": "भुगतान अवधि (दिन)",
    "merchant.notInGrandTotal": "महायोग में नहीं",

    "jins.title": "जिंस", "jins.sub": "जो किस्में आप खरीदते-बेचते हैं",
    "jins.add": "जिंस जोड़ें", "jins.code": "कोड", "jins.name": "नाम",
    "jins.crop": "फ़सल", "jins.crop.paddy": "धान", "jins.crop.wheat": "गेहूँ",
    "jins.crop.maize": "मक्का", "jins.crop.other": "अन्य",

    "users.title": "उपयोगकर्ता", "users.sub": "कौन इसे चला सकता है, और क्या कर सकता है",
    "users.add": "उपयोगकर्ता जोड़ें", "users.edit": "उपयोगकर्ता बदलें", "users.role": "भूमिका",
    "users.setPin": "पिन तय करें", "users.resetPin": "पिन रीसेट करें", "users.unlock": "खोलें",
    "users.locked": "बंद", "users.lockedUntil": "{min} मिनट के लिए बंद",
    "users.owner": "स्वामी", "users.overrides": "अतिरिक्त अनुमतियाँ",
    "users.overridesSub": "भूमिका के ऊपर। मनाही हमेशा भारी पड़ती है।",
    "users.effectivePerms": "{n} अनुमतियाँ",
    "users.lastOwner": "यही एकमात्र स्वामी है। पहले किसी और को स्वामी बनाएँ।",
    "users.you": "आप",

    "roles.title": "भूमिका व अनुमतियाँ", "roles.sub": "हर भूमिका ठीक क्या कर सकती है",
    "roles.add": "भूमिका जोड़ें", "roles.key": "कुंजी", "roles.label": "नाम",
    "roles.builtIn": "अंतर्निहित", "roles.userCount": "{n} उपयोगकर्ता",
    "roles.ownerLocked": "स्वामी भूमिका के पास सारी अनुमतियाँ हमेशा रहती हैं।",
    "roles.selectAll": "सब चुनें", "roles.clearAll": "सब हटाएँ",
    "roles.permCount": "{total} में से {n}",

    "audit.title": "ऑडिट", "audit.sub": "हर बदलाव, किसने किया और पहले क्या था",
    "audit.filterEntity": "प्रकार", "audit.filterUser": "उपयोगकर्ता",
    "audit.filterAction": "क्रिया", "audit.loadMore": "पुराने देखें",
    "audit.empty": "अभी कुछ दर्ज नहीं", "audit.changed": "बदला",
    "audit.before": "पहले", "audit.after": "बाद में", "audit.noChange": "कोई खाना नहीं बदला",
    "audit.searchPlaceholder": "नाम, उपयोगकर्ता या क्रिया से खोजें",
    "audit.readOnly": "यह रिकॉर्ड कोई भी बदल या हटा नहीं सकता।",

    "dash.title": "डैशबोर्ड", "dash.comingSoon": "अगले चरण में बन रहा है",
    "dash.setupChecklist": "सेटअप पूरा करें", "dash.setupSub": "दैनिक सूची शुरू करने से पहले कुछ बातें भर लें",
    "dash.stepBusiness": "व्यापार का पता व लाइसेंस", "dash.stepMills": "मिल जोड़ें",
    "dash.stepSuppliers": "आढ़ती जोड़ें", "dash.stepUsers": "कर्मचारी जोड़ें",
    "dash.stepDone": "हो गया", "dash.stepTodo": "बाकी है",
    "dash.suppliers": "आढ़ती", "dash.mills": "मिल", "dash.commodities": "जिंस", "dash.staff": "कर्मचारी",

    "err.noPermission": "आपको इसकी अनुमति नहीं है",
    "err.noPermissionSub": "किसी स्वामी से {perm} अनुमति माँगें।",
    "err.offline": "सर्वर से संपर्क नहीं हो रहा",
    "err.offlineSub": "स्थानीय सेवा रुक गई होगी। जाँचें कि वह चल रही है, फिर दोबारा कोशिश करें।",
  },
} as const;

export type Lang = keyof typeof STRINGS;
export type StringKey = keyof typeof STRINGS["en"];
